name: systemd
on: push
jobs:
  build_pkg:
    uses: gardenlinux/package-build/.github/workflows/build_pkg.yml@main
    with:
      build_options: nocheck noudeb terse
      build_profiles: nocheck noudeb
